msmnile_gvmq: Refine for R
1. The change is based on msmnile_gvmq in Q

   (1) reference branch: qcom-devices-auto.lnx.2.0
   revision: 75bd9e3353f3d64a56a1cb945da3f258cc3e0bca

   (2) formalize code

   (3) remove un-used code commented in "#"

2. AndroidBoard.mk

   Include "vendor/qcom/opensource/core-utils/build/AndroidBoardCommon.mk".

   Otherwise, the build error is exposed in "system/memory/libion/include/ion/ion.h"
   when to compile mm-video-v4l2 and gles.

   "error: unknown type name 'ion_user_handle_t'"

3. AndroidProducts.mk

   Add "msmnile_gvmq-user" in "COMMON_LUNCH_CHOICES".

4. BoardConfig.mk

   (1) Correct out path in "BOARD_PREBUILT_DTBOIMAGE" as "msmnile_gvmq"

   (2) Change "BOARD_SYSTEMSDK_VERSIONS" as "29"

5. msmnile_gvmq.mk

   (1) Disable AV value-added feature
   TARGET_FWK_SUPPORTS_AV_VALUEADDS := false
   TARGET_FWK_SUPPORTS_FULL_VALUEADDS := false

   Otherwise, mm-parser "libmmparserextractor" can't be
   built out due to the error below in "MediaDefs.h"

   "error: use of undeclared identifier 'kAudioEncodingPcm24bitPacked'"
   "error: use of undeclared identifier 'kAudioEncodingPcm32bit'"

   (2) Include WLAN driver only if "BOARD_HAS_QCOM_WLAN" is true

Change-Id: Ie24f4af449a12424568e85e399823b766d3b981f